# Project: Ober0
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = error.o gen.o location.o o.o ovm.o pars.o scan.o table.o text.o ovmtobin.o
LINKOBJ  = error.o gen.o location.o o.o ovm.o pars.o scan.o table.o text.o ovmtobin.o
LIBS     = -L"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32
INCS     = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ober0.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

error.o: error.c
	$(CC) -c error.c -o error.o $(CFLAGS)

gen.o: gen.c
	$(CC) -c gen.c -o gen.o $(CFLAGS)

location.o: location.c
	$(CC) -c location.c -o location.o $(CFLAGS)

o.o: o.c
	$(CC) -c o.c -o o.o $(CFLAGS)

ovm.o: ovm.c
	$(CC) -c ovm.c -o ovm.o $(CFLAGS)

pars.o: pars.c
	$(CC) -c pars.c -o pars.o $(CFLAGS)

scan.o: scan.c
	$(CC) -c scan.c -o scan.o $(CFLAGS)

table.o: table.c
	$(CC) -c table.c -o table.o $(CFLAGS)

text.o: text.c
	$(CC) -c text.c -o text.o $(CFLAGS)

ovmtobin.o: ovmtobin.c
	$(CC) -c ovmtobin.c -o ovmtobin.o $(CFLAGS)
